# apiVersion: networking.istio.io/v1
# kind: VirtualService
# metadata:
#   labels:
#     app.kubernetes.io/instance: tool-crbioportal-apiserver-manual
#     app.kubernetes.io/name: tool-crbioportal-apiserver-manual
#   name: tool-crbioportal-apiserver-manual
#   namespace: ds1
# spec:
#   gateways:
#   - gravity-system/wl2-istio-gravity-default
#   hosts:
#   - '*'
#   http:
#   - headers:
#       request:
#         set:
#           x-original-request-uri: /scitools/ds1/apps/crbioportal-apiserver/
#     match:
#     - uri:
#         prefix: /scitools/ds1/apps/crbioportal-apiserver/
#     route:
#     - destination:
#         host: tool-crbioportal-apiserver.ds1.svc.cluster.local
#         port:
#           number: 80
#     corsPolicy:
#       allowHeaders:
#       - Content-Type
#       - content-type
#       allowMethods:
#       - GET
#       - POST
#       - PUT
#       - DELETE
#       - PATCH
#       - HEAD
#       - OPTIONS
#       allowOrigins:
#       - exact: "*"
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  labels:
    app.kubernetes.io/instance: tool-crbioportal-manual
    app.kubernetes.io/name: tool-crbioportal-manual
  name: tool-crbioportal-manual
  namespace: ds1
spec:
  gateways:
  - gravity-system/wl2-istio-gravity-default
  hosts:
  - '*'
  http:
  - headers:
      request:
        set:
          x-original-request-uri: /scitools/ds1/apps/crbioportal/
    match:
    - uri:
        prefix: /scitools/ds1/apps/crbioportal/
    route:
    - destination:
        host: tool-crbioportal.ds1.svc.cluster.local
        port:
          number: 80
    corsPolicy:
      allowHeaders:
      - Content-Type
      - Accept
      allowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - HEAD
      - OPTIONS
      allowOrigins:
      - exact: http://localhost:3000/
      - exact: http://localhost:4200/